# Generated by Django 4.2.8 on 2024-05-01 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_diapositiva_subtitulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentacion',
            name='nombre_archivo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
