# Generated by Django 4.2.8 on 2024-05-09 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_presentacion_nombre_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentacion',
            name='vista_previa',
            field=models.ImageField(blank=True, null=True, upload_to='vistas_previas/'),
        ),
    ]
