# Generated by Django 4.2.8 on 2024-04-13 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='presentacion',
            old_name='titulo',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='diapositiva',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='diapositiva',
            name='orden',
        ),
        migrations.RemoveField(
            model_name='diapositiva',
            name='titulo',
        ),
        migrations.RemoveField(
            model_name='diapositiva',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='presentacion',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='presentacion',
            name='usuario',
        ),
    ]
